server:
  port: 5000
bot:
  token: ${BOT_TOKEN}
  name: ${BOT_NAME}
  path: ${BOT_PATH}
  mainchat: ${MAIN_CHAT}
home:
  proto: ${HOME_CONNECTION_PROTOCOL}
  ip: ${HOME_CONNECTION_IP}
  port: ${HOME_CONNECTION_PORT}
logging:
  level:
    org.rch.jarvisapp: FATAL